### ISSUE TITLE
Need to generate migration

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-building-post-patch-delete-api-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/208454?module_item_id=480487

### Concern

We tell students that they can pick up where we left off from a previous lesson by simply running `flask db upgrade`, but we actually still need to generate the migration itself. We can either include instructions for that or include the migration file in our repo.

**Comment by TylerTaylor** [comment]
I mistakenly created another issue about this before checking - but this is still an issue and we've gotten a few questions about it this morning

**Comment by pgill97** [comment]
@TylerTaylor  A migration has now been added to the repo. Let me know if there are any issues with it.
