### ISSUE TITLE
Issue creating seed data

### ISSUE THREAD

**Issue by jacoblogan98** [learn-co-curriculum/python-p4-building-post-patch-delete-api-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/208454?module_item_id=480487

### Concern

When setting up this lab, we are told to run `python seed.py`. Upon doing so, I'm getting an error from line 10 on seed.py that reads: 
  
   RuntimeError: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.

After commenting out line 10, I was able to seed the database. This is odd because I did not have this issue on the previous lessons that also initialized the db in the seeds file.

**Comment by professor-ben** [comment]
Hi Jacob,

Thanks for raising this issue. Look forward to a fix later today.

-Ben
