### ISSUE TITLE
Passing tests in VSCode but failing in CodeGrade

### ISSUE THREAD

**Issue by lslayman** [learn-co-curriculum/python-p4-building-post-patch-delete-api-lab#5]
### Canvas Link

https://learning.flatironschool.com/courses/6330/assignments/239803?module_item_id=563970

### Concern

Hi! I experienced this issue when completing the building-get-api-lab, but I'm once again receiving a failing grade for this assignment in CodeGrade despite all of my tests passing in VSCode. Please advise!

**Comment by linda-seiter** [comment]
codegrade updated
